PROGRESS..

diff --git a/jamx-gen-spec b/jamx-gen-spec
--- a/jamx-gen-spec
+++ b/jamx-gen-spec
@@ -14,37 +14,39 @@
 #===============================================================================
 
 #set -o nounset                              # Treat unset variables as an error
+DIRNAME=`dirname $0`
+NEEDED_FILES="/home/jamx/etc/jamx.rc $DIRNAME/jamx-functions.rc"
+for NEEDED_FILE in $NEEDED_FILES;do
+        if [ ! -r $NEEDED_FILE ];then
+                echo "Missing $NEEDED_FILE. Something is wrong with your ENV. Exiting."
+                exit 1
+        fi
+        . $NEEDED_FILE
+done
+if [ ! -r "$1" ];then
+        echo "Usage: $0 </path/to/package.rc>"
+        exit 1
+fi
+PACKAGE_RC=$1
+#
+. $PACKAGE_RC
+cp /home/jamx/etc/spec-skelatons/rpm/skel.spec ~/$PACKAGE_NAME.spec
+replace_tokens $PACKAGE_RC ~/$PACKAGE_NAME.spec
+
 	
-- analyze source for build and runtime dependencies
-- generate spec 
-      - description
-      - source URL
-      - license - try to auto detect looking for files named license/i or copyright/i
-      - arch - try to auto detect whether noarch/indep according to source type. For example, if the source is PHP||Perl||Python||many others only, then it is indep.
-      - changelog
-	- for deb we have debchange and dh-make already takes care of the initial import
-	- need a parallel for RPM
-      - auto detect config files
-      - dev package
-      - maintainer 
-	- check MAIL and DEBEMAIL ENV vars for email
-	- check DEBFULLNAME and MAINTAINER_NAME for name
 
-For deb packages dh_make makes a sound base for generating skeleton files, we then need to add the missing pieces.
-For RPMs a new tool will need to be created
-
-prepare_source()
-{
+#prepare_source()
+#{
 #	- fetch and extract
 # 	- 
-}
+#}
 
-is_arch_indep()
-{
+#is_arch_indep()
+#{
+#
+#}
 
-}
-
-detect_deps()
-{
-
-}
+#detect_deps()
+#{
+#
+#}
diff --git a/jamx-prepare-build-env b/jamx-prepare-build-env
--- a/jamx-prepare-build-env
+++ b/jamx-prepare-build-env
@@ -15,6 +15,15 @@
 #===============================================================================
 
 #set -o nounset                              # Treat unset variables as an error
+DIRNAME=`dirname $0`
+NEEDED_FILES="$DIRNAME/jamx.rc $DIRNAME/jamx-functions.rc $DIRNAME/colors.rc"
+for NEEDED_FILE in $NEEDED_FILES;do
+        if [ ! -r $NEEDED_FILE ];then
+                echo "Missing $NEEDED_FILE. Something is wrong with your ENV. Exiting."
+                exit 1
+        fi
+        . $NEEDED_FILE
+done
 
 
 . /home/jamx/etc/jamx.rc
@@ -32,4 +41,17 @@ fi
 set -e
 git config --global user.email $MAINTAINER_EMAIL 
 git config --global user.name $MAINTAINER_NAME
+mkdir -p ~/build/tmp
+cd ~/build/tmp
+wget $SOURCE_URL
+ARCHIVE_NAME=`echo $SOURCE_URL|awk -F "/" '{print $NF}'`
+if file $ARCHIVE_NAME|grep -i zip ;then
+        EXTRACT_COMMAND="unzip"
+else
+        EXTRACT_COMMAND="tar xvf"
+fi
+$EXTRACT_COMMAND $ARCHIVE_NAME
+#- remove {.git,.csv,.svn} files
+#- set proper permissions on files, i.e: remove redundant/add exec bit where needed
+# if the first line of the file is "^#!" - we need to set exec bit on
 
